### ISSUE TITLE
v0.0.8 breaks Kodi 18 support

### ISSUE THREAD

**Issue by pr11t** [yllar/plugin.video.jupiter.err.ee#4]
The latest update seems to break support for Python 2 that Kodi 18 uses. Kodi 19 is unfortunately not yet available from Raspbian repos.

First it fails to find the modules:
```
Error Type: <type 'exceptions.ImportError'>
Error Contents: No module named resources.lib.errlib.menu
Traceback (most recent call last):
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 18, in <module>
    from resources.lib.errlib.menu import Menu
ImportError: No module named resources.lib.errlib.menu
-->End of Python script error report<--
```
I guess Python3 handles it differently, but to get it working I had to create `__init__.py` file in resources directory.

After that I get encoding errors:
```
Error Type: <type 'exceptions.UnicodeDecodeError'>
Error Contents: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Traceback (most recent call last):
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 293, in <module>
    router(sys.argv[2][1:])
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 277, in router
    get_category(params['category'])
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 113, in get_category
    for category in categories.get_categories():
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/resources/lib/errlib/category.py", line 23, in get_categories
    if 'Jätka' not in category['header']:  # filter it out for now as we don't have session support
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

Fixed by adding the magic encoding comment and importing `unicode_literals`.

Here is the fixed code: https://github.com/pr11t/plugin.video.jupiter.err.ee/commit/b7516dd31a4e14007a74e0d443923f5fbde96ed2
I haven't tested it with Kodi 19/Python3 though.

**Comment by yllar** [comment]
Should work with 0.0.9 Thanks!
